### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by LeonardoBarneschi** [atomistic-machine-learning/field_schnet#2]
Hi,  I have tried to use field_schnet. 
On the installation side, everything looks fine, but when I tried to call "field_schnet_run.py" for the very first test in the README of field_schnet I get the following error.

Traceback (most recent call last):
  File "/home/Leo/field_schnet/./src/scripts/field_schnet_run.py", line 10, in <module>
    from field_schnet.utils.script_utils import evaluate_dataset
  File "/home/Leo/.local/lib/python3.10/site-packages/field_schnet/__init__.py", line 2, in <module>
    from field_schnet import atomistic
  File "/home/Leo/.local/lib/python3.10/site-packages/field_schnet/atomistic/__init__.py", line 1, in <module>
    from field_schnet.atomistic.model import *
  File "/home/Leo/.local/lib/python3.10/site-packages/field_schnet/atomistic/model.py", line 5, in <module>
    from schnetpack import Properties
ImportError: cannot import name 'Properties' from 'schnetpack' (/home/Leo/.local/lib/python3.10/site-packages/schnetpack/__init__.py)

Looks like indeed in the __init__ file of schnetpack, "Properties" is being imported but with lower case p (properties). 

Could you please help me figure out what I could possibly be doing wrong?

**Comment by LeonardoBarneschi** [comment]
Sorry, for posting here again, but it looks like it might be solved downgrading the schnetpack package. With schnetpack=0.30 it seems to be working. A lot of schnetpack constructs called by field_schnet looks very different in latest versions of schnetpack.
